name: test
channels:
  - defaults
  - conda-forge
dependencies:
    # Base depends
  - numpy
  - nomkl
  - python
  - pint
  - pydantic>=1.0.0

    # Optional depends
  - networkx>=2.4.0
  - py3dmol

    # Testing
  - pytest>=4.0.0
  - pytest-cov
  - codecov
  - scipy  # tests an aspect of a helper fn not used by qcel functionality
