name: test
channels:
  - defaults
  - conda-forge
dependencies:
    # Base depends
  - numpy
  - nomkl
  - python
  - pint
  - pydantic

    # Testing
  - pytest
  - pytest-cov
  - codecov

    # Pip depends
  - pip:
    - deepdiff # Only used for testing some areas
