name: test
channels:
  - defaults
  - conda-forge
dependencies:
    # Base depends
  - numpy
  - nomkl
  - python
  - pydantic

    # Testing
  - pytest
  - pytest-cov

    # Pip depends
  - pip:
      # Base depends
    - pint

      # Testing
    - codecov
    - deepdiff
