name: qcelemental-docs
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3
    - numpy
    - sphinx
    - sphinx_rtd_theme
    - sphinx-automodapi
    - graphviz
    - pip:
      - pydantic
